version: '3'
services:
    nginx:
        restart: always
        image: ninexty/nginx:latest
        build: ./nginx
        ports: ["80:80"]
        volumes: ["staticfiles:/static", "mediafiles:/media"]
        links: [webapp]

    webapp:
        restart: always
        image: ninexty/backtester:latest
        build: ./webapp
        expose: ["8000"]
        volumes: ["staticfiles:/DjangoBacktester/static", "mediafiles:/DjangoBacktester/media"]
volumes:
    staticfiles:
    mediafiles:
