version: '3'
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        volumes:
            - dbdata:/var/lib/mysql

    wordpress:
        depends_on:
            - db
        image: wordpress:fpm
        restart: always
        volumes: 
            - wpdata:/var/www/html
        expose: 
            - "9000"
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_PASSWORD: wordpress

    nginx:
        depends_on:
            - wordpress
            - backtester
        restart: always
        image: ninexty/nginx:latest
        build: ./nginx
        ports: ["80:80"]
        volumes:
            - staticfiles:/backtester/static
            - mediafiles:/backtester/media
            - wpdata:/var/www/html
        links: 
            - backtester
            - wordpress

    backtester:
        restart: always
        image: ninexty/backtester:latest
        build: ./backtester
        expose: 
            - "8000"
        volumes: ["staticfiles:/DjangoBacktester/static", "mediafiles:/DjangoBacktester/media"]
volumes:
    dbdata:
    wpdata:
    staticfiles:
    mediafiles:

